repos:
  - id: github.com/lhenn-au/atlantis-example
    apply_requirements: [approved, mergeable]
    workflow: myworkflow
policies:
  owners:
    users:
      - lhenn-au
  conftest_version: 0.35.0
  policy_sets:
    - name: example-conf-tests
      path: /Users/laurahenn/repos/atlantis-example/policies
      source: local
workflows:
  myworkflow:
    plan:
      steps:
      # - run: echo "dir is $DIR"
      # - run: rm -rf .terraform || true
      - init
      - plan
    policy_check:
      steps:
        - show
        - policy_check:
            extra_args: ["-p /Users/laurahenn/repos/atlantis-example/policies/", "--all-namespaces"]
