repos:
  - id: github.com/lhenn-au/atlantis-example
    apply_requirements: [approved, mergeable]
    workflow: myworkflow
workflows:
  myworkflow:
    plan:
      steps:
      - run: echo "dir is $DIR"
      - run: git clone git@github.com:lhenn-au/atlantis-example.git
      - run: pwd; ls
      - run: echo "dir is $DIR"
      - run: "$DIR/atlantis-example/my-custom-script.sh"
      # - run: cd "$DIR"
      # - run: pwd; ls
      - init
      - plan
