repos:
  - id: github.com/lhenn-au/atlantis-example
    apply_requirements: [approved, mergeable]
workflows:
  myworkflow:
    plan:
      steps:
      - run: ./my-custom-script.sh
      - init
      - plan
