repos:
  - id: github.com/lhenn-au/atlantis-example
    apply_requirements: [approved, mergeable]
    workflow: myworkflow
policies:
  owners:
    users:
      - lhenn-au
  conftest_version: 0.35.0
  policy_sets:
    - name: example-policies
      path: /Users/laurahenn/atlantis-policy-test/policies
      source: local
workflows:
  myworkflow:
    plan:
      steps:
      - init
      - plan
    policy_check:
      steps:
        - env:
            name: POLICY_DIR
            command: 'echo "-p ../policies"'
        - run: "$DIR/atlantis-example/pull-policies.sh"
        - policy_check: 
        # This would be replaeced with the same code
            extra_args: ["/Users/laurahenn/atlantis-policy-test/policies", "--all-namespaces"]
