repos:
  - id: github.com/lhenn-au/atlantis-example
    apply_requirements: [approved, mergeable]
    workflow: myworkflow
policies:
  owners:
    users:
      - lhenn-au
  conftest_version: 0.35.0
  policy_sets:
    - name: example-policies
      # path on my local computer, in reality would be a some filepath in the container   
      path: /Users/laurahenn/atlantis-policy-test/policies
      source: local
workflows:
  myworkflow:
    plan:
      steps:
      - init
      - plan
    policy_check:
      steps:
        - env:
            name: PULL_POLICY_SCRIPT
            command: echo "$(git rev-parse --show-toplevel)/policies"
        - run: "$PULL_POLICY_SCRIPT"
        - run: echo "dir is now $(pwd)"
        - show
        - policy_check
